export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  EMPLOYEES: '/employees',
  EMPLOYEE_ADD: '/employees/add',
  EMPLOYEE_EDIT: '/employees/edit/:id',
  EMPLOYEE_VIEW: '/employees/view/:id',
  SALARY: '/salary',
  SALARY_GENERATE: '/salary/generate',
  SALARY_HISTORY: '/salary/history',
  LEAVES: '/leaves',
  LEAVES_ADD: '/leaves/add',
  LEAVES_REQUESTS: '/leaves/requests',
  LEAVES_HISTORY: '/leaves/history',
  REPORTS: '/reports',
  REPORTS_EMPLOYEE: '/reports/employees',
  REPORTS_SALARY: '/reports/salary',
  REPORTS_LEAVE: '/reports/leaves',
  SETTINGS: '/settings',
};
